### ISSUE TITLE
Customs Offices should not show on Asset Page (calculating m3 in a system)

### ISSUE THREAD

**Issue by ccatlett1984** [eve-seat/seat#106]
![customs_offices](https://cloud.githubusercontent.com/assets/7456217/3127044/a7bac404-e7b2-11e3-8329-fad7c367949b.JPG)

Since once deployed you can't pick them back up, we shouldn't list a m3 value.

**Comment by leonjza** [comment]
Closing this as this repository is no longer supported. Please refer to the latest, supported version here: [https://github.com/eveseat/seat](https://github.com/eveseat/seat).
