### ISSUE TITLE
Extend Member Security Page to consider Titles

### ISSUE THREAD

**Issue by smokie128** [eve-seat/seat#148]
Hi,

would it be possible that the Member Security Page considered Roles granted by Titles, too? In my corp we actually handle almost everything by titles, so the page doesn't contain much information at all.

**Comment by smokie128** [comment]
Yep, looks better.
I remember the "EVE Corp Management" tool (basically another SeAT) which assigned every role a point value and summarized these points for every character in the corp, so you could see who poses the biggest danger in case someone goes rogue. Sadly, the project died some time ago, but it'd be great to have that functionality back.

Maybe add an option to assign some of the point values yourself (derived from a default set).
That would for example enable you to differ between take rights on your corp garbage hangar and take rights on your moongoo & Exotic Dancers hangar.

**Comment by LunarchildEU** [comment]
At the moment there is no direct mapping from the individual EVE role (like in the UI) to the Webfrontend. Will look into it, there should be some way to map the Role to Hangar Division.

One Role per line for both Member Roles and Titles like that ?
![image](https://cloud.githubusercontent.com/assets/2454083/5593583/1144293c-9218-11e4-8769-1dccb09f58aa.png)

And what about listing the People that have a certain Title assigned under the assigned permissions it got, that could be a step into that direction.

**Comment by LunarchildEU** [comment]
Got something to tease...
![image](https://cloud.githubusercontent.com/assets/2454083/5598340/dd0ba6f2-92b4-11e4-9c6e-3eb9ce246f6b.png)

.. but some one is going to slap me for that one ..
![image](https://cloud.githubusercontent.com/assets/2454083/5598351/0e2ca5ba-92b5-11e4-818a-f1a7bf9b974f.png)

.. and not to mention that there still is some room for the Characters who have that Title.

**Comment by eve-seat** [comment]
geez that code looks so complex lol :(

**Comment by LunarchildEU** [comment]
Arg, a regex on the roleName would have been shorter.

**Comment by eve-seat** [comment]
:P

**Comment by t3rminalVel0city** [comment]
0_0

**Comment by smokie128** [comment]
looks nice!

**Comment by eve-seat** [comment]
This was done?
