### ISSUE TITLE
Enhancement: Add links to EVE-Kill, EVE WHO, etc. to character screen.

### ISSUE THREAD

**Issue by ccatlett1984** [eve-seat/seat#155]
![capture](https://cloud.githubusercontent.com/assets/7456217/3565537/b01a80a6-0abe-11e4-93bb-363086520287.JPG)

Should be an easy add. the url's are as follows:
EVE-Kill - http://eve-kill.net/?a=pilot_detail&plt_external_id=charid
EVE WHO - http://evewho.com/pilot/charname
EVEBoard - http://eveboard.com/pilot/charname
EVE-Search - http://eve-search.com/search/author/charname
EVE Gate - https://gate.eveonline.com/Profile/charname

**Comment by LunarchildEU** [comment]
Got a proposal for that - does it fit under the Character Image?
![image](https://cloud.githubusercontent.com/assets/2454083/5696405/8df058ce-99d0-11e4-8cbd-4a9b131b6808.png)

**Comment by ccatlett1984** [comment]
I think that would be a good place, don't waste space that way.

**Comment by eve-seat** [comment]
So this is cool. While we on this topic though, what are the thoughts of moving the tabs in the character details view to the left side to run vertical?

**Comment by eve-seat** [comment]
This is done.
