### ISSUE TITLE
Sort POS Modules by category

### ISSUE THREAD

**Issue by smokie128** [eve-seat/seat#170]
Hi,

i think it would be great to have the POS modules in the Starbase Details -> Module Details screen sorted by (collapsable) categories. I think it's rather annoying to have all the guns and other stuff together with the information you need.

Proposal for categories: Industry, Storage, Defense (like in the game), maybe even subdivide Industry into Moon Mining and other industry.

**Comment by eve-seat** [comment]
I have commited 84bede2e51b1f15f3b101c523f1366bc70362922, which I think may help with this? @smokie128 mind giving it a test run?

**Comment by eve-seat** [comment]
Screeny:

![pos](http://i.imgur.com/Bj5rKr1.png)

**Comment by smokie128** [comment]
Yes, it's getting there. Still feels a bit bulky though.
![screenshot 2015-01-01 22 16 03](https://cloud.githubusercontent.com/assets/3704376/5593315/997221ce-9204-11e4-97ec-f587eeb27c08.png)
Maybe group the modules together in expandable categories, as i said above...

Category **Industry** would include Moon Harvesting Arrays, Coupling Arrays, Assembly Arrays, Refineries, Laboratories, etc.

Category **Storage** would include Silos, PHA's, CHA's, SMA's, etc.

Category **Defense** would include Guns, Hardeners, EWAR, etc.

And within the category sort by storage capacity, so in Industry you would have the Silo's above the coupling arrays.
Also, if possible include some visual hint, so that it's obvious that the panels are collapsible (like the - / + signs in the Starbase Summaries panel).

**Comment by eve-seat** [comment]
Like the categories idea. Will definitely work a little on this and see what I can come up with.

**Comment by eve-seat** [comment]
I did some grouping work for this now. I totally understand why CCP is dragging their feet with POS cause code because its totally not a fun thing to work with!

**Comment by smokie128** [comment]
#315 tries to improve on the design. Have a look at it!

**Comment by eve-seat** [comment]
Done.
