### ISSUE TITLE
Undefined offset: 40287936 (View: /var/www/seat/app/views/corporation/starbase/starbase.blade.php)

### ISSUE THREAD

**Issue by vpitoscia** [eve-seat/seat#272]
ErrorException
Undefined offset: 40287936 (View: /var/www/seat/app/views/corporation/starbase/starbase.blade.php)
open: /var/www/seat/app/storage/views/6cc40432be96660311e23670713fce68
```
								    		make a note about it
								    	*/ ?>
								    	<?php if ($details->moonID == 0): ?>
								    		<tr>
								    			<td colspan="3">Unknown MoonID, unable to find assets</td>
								    		</tr>
								    	<?php else: ?>
										    <?php foreach ($item_locations[$details->moonID] as $item): ?>
 
										    	<?php /* 
```
I have about a half dozen corp APIs, and only one is having this issue. Let me know if I can check the data for any particular conditions that might explain this to help debug.

**Comment by eve-seat** [comment]
I believe this problem is solved since 84bede2e51b1f15f3b101c523f1366bc70362922.
