### ISSUE TITLE
[Enhancement] Participation links

### ISSUE THREAD

**Issue by smokie128** [eve-seat/seat#288]
Could SeAT implement a PAP link system?
PAP links are links that are to be visited via IGB, which transmits additional data (e.g. Pilot X was in System Y in Ship Z, at time A.) that the server then stores.
A number of alliances use these systems, but i failed to find an open source one, and since we already use SeAT, I thought why not implement it?

**Comment by ccatlett1984** [comment]
The IGB will die "very soon", this was discussed @ fanfest this year.
They have a few things to move into the api, once that is does IGB goes bye bye.
