### ISSUE TITLE
[Bug] CustomsOffice update: Trying to get property of non-object

### ISSUE THREAD

**Issue by smokie128** [eve-seat/seat#312]
Stacktrace: http://pastebin.com/p3FqN7xg

**Comment by eve-seat** [comment]
Ping @LunarchildEU could you have a look at this one?

**Comment by LunarchildEU** [comment]
Please execute the following querys in your DB:
`select itemID, locationID from corporation_assetlist where itemID = 1012674593736;`

locationID is needed for next Query:
`select count(*) from mapDenormalize where mapDenormalize.groupID = 7 and mapDenormalize.solarSystemID = <locationID>;`

That should yield at least the rowcount for the certain System, if not please execute `select count(*)  from mapDenormalize;`.

These querys all should return somthing > 0.

**Comment by smokie128** [comment]
```sql
mysql> select itemID, locationID from corporation_assetlist where itemID = 1012674593736;
+---------------+------------+
| itemID        | locationID |
+---------------+------------+
| 1012674593736 |   30003054 |
+---------------+------------+
1 row in set (0.01 sec)

mysql> select count(*) from mapDenormalize where mapDenormalize.groupID = 7 and mapDenormalize.solarSystemID = 30003054;
+----------+
| count(*) |
+----------+
|       10 |
+----------+
1 row in set (0.00 sec)
```

**Comment by LunarchildEU** [comment]
Currently the function that pops this error relies that the POCO is already in the AssetList table of the Corporation, which sadly turns out it is not good.

* Assetlist ~7h Cache
* CustomsOffice ~1h Cache

That could have caused the problem - 9a14350cd4437502fdfc7c772171a53fd7eddb7e should sort that out.

**Comment by eve-seat** [comment]
Sweet. @smokie128 can you test @LunarchildEU fix and let us know?

**Comment by smokie128** [comment]
Tested #313
Working fine so far. Issued a full update on the corp key, finished without errors.
