### ISSUE TITLE
issue with mail search (and fix)

### ISSUE THREAD

**Issue by freedenizen** [eve-seat/seat#322]
Dashboard controller mail search has a problem, the search shows all results regardless of group membership, the issue is due to the orwhere clauses but there is a fix:

https://github.com/eve-seat/seat/blob/dev/app/controllers/DashboardController.php#L160

should be:
                ->where(function($query)
                {
                    $query->where('character_mailmessages.senderName', 'like', '%' . Input::get('q') . '%')
                    ->orWhere('character_mailmessages.title', 'like', '%' . Input::get('q') . '%')
                    ->orWhere('character_mailbodies.body', 'like', '%' . Input::get('q') . '%');
                });

**Comment by LunarchildEU** [comment]
I could reproduce that and the fix looks working, but the view also shows the receiver's corporation as that of the sender.
