### ISSUE TITLE
Issue with API updates

### ISSUE THREAD

**Issue by Regner** [eve-seat/seat#332]
Hey,

I installed SeAT at home last night for personal use. Got it installed fine, able to log in, add API keys, and information from the API keys seems to have been added. However it doesn't seem to be running any kind of API updates.

The queue only shows tasks from the original API import. The cron is setup as described in the docs: `* * * * * /usr/bin/php /var/www/seat/artisan scheduled:run 1>> /dev/null 2>&1`

Any suggestion on what the issue could be?

**Comment by Nutbolt52** [comment]
Do you have the supervisor workers running? During the install you would have set up a number of these. Check they are running on the server (process name is supervisord I believe).

**Comment by Regner** [comment]
Yes, they are running. The queue is empty though. If I go into the details of an API key and tell it to update the key the task gets added to the queue and run fine.

**Comment by Nutbolt52** [comment]
Interesting. Well that's the limit of my technical know how. I would suggest joining the IRC channel at #wcs-pub on irc.coldfront.net. Normally people around, logged in at work etc... 

Although how many API keys do you have added? SeAT only sends jobs to works on a certain schedule. Perhaps simply haven't seen one yet? Or I guess a simple test, does the server status get updated? If thats not getting updated then issue with the workers I think.

**Comment by Regner** [comment]
I will check into that, and join the IRC channel, when I get back from
these CSM meetings. Thanks for the help! :)

**Comment by eve-seat** [comment]
Tough one. Especially since queuing a update manually works.

A few things to check (in no particular order) would be:
- [ ] Does `php artisan seat:diagnose` (run as the user the workers are running as) return any errors?
- [ ] Can the workers write to the `app/storage/logs/laravel.log` log file?
- [ ] Any critical errors (apart from API warnings) in `app/storage/logs/laravel.log`?
- [ ] Does running `/usr/bin/php /var/www/seat/artisan scheduled:run` (from the cronjob) return any output? (It shouldn't)
- [ ] Is cron running?

HTH

**Comment by Regner** [comment]
Thanks guys! That seat:diagnose command is wonderful. Ran it and got:

```bash
root@SeAT:/var/www/seat# sudo -u www-data /usr/bin/php /var/www/seat/artisan seat:diagnose
Running SeAT 0.13.0 Diagnostics

If you are not already doing so, it is reccomended that you run this as the user the workers are running as.
Eg: `sudo -u apache /usr/bin/php /var/www/seat/artisan seat:diagnose`.
This allows you to ensure the correct permissions are in place as required.

SeAT configuration:
[ok] Debug Mode On: No
Url: http://localhost
Failed API limit: 20
Ban count time: 1440 minutes

Logging:
[error] /var/www/seat/app/storage/logs/laravel.log is not writable.

Database configuration:
Database driver: mysql
MySQL Host: 192.168.1.121
MySQL Database: seat
MySQL Username: seat
MySQL Password: ********************

Database connection test...
[ok] Successfully connected to database `seat` (did not test schema)

Redis configuration:
Redis Host: 127.0.0.1
Redis Port: 6379

Redis connection test...
[ok] Successfully set the key: ZbNZAVGbHriuxGRE5xQCrKwWahaPawxrpR565XTC and set it to expire in 10 seconds
[ok] Successfully retreived key: ZbNZAVGbHriuxGRE5xQCrKwWahaPawxrpR565XTC which has value: 2015-01-20 16:14:31

EVE API call test with phealng...
[ok] Testing the ServerStatus API call returned a response reporting 25717 online players, with the result cache expiring 1 minute from now
```

I then did another chmod on app/storage to fix the permission issue. Diagnose came back clean, waited for CRON to run, and saw the ServerStatus along with some CorporationWallet updates get run. I could have sworn I ran that chmod command, but eh.

It still seams like more of the API pages should be getting updated, but I will give it time and see.

**Comment by eve-seat** [comment]
Great news! FYI `php artisan schedule:summary` will give you the cron-like schedule of the workers =)

**Comment by Regner** [comment]
:D Thanks! And yes, now that I have given it some more time and looking at the job history lots of things have been happening. Thank you so much guys for the quick and awesome responses.
