### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by SandyVaJJ** [eve-seat/seat#333]
Im having some issues installing seat, it keeps failing at this stage. If anyone could help or tell if i did anything wrong. I am following the centos instructions and using centos 7

php artisan seat:install

[Illuminate\Database\QueryException]                                                                         
SQLSTATE[HY000]: General error: 1364 Field 'last_login' doesn't have a default value (SQL: insert into `seat_users` (`username`, `password`, `email`, `activated`, `updated_at`, `created_at`) values (admin, ygD/IDRt  
  ziNcX1aMGnxHruhoUjBwkKxGbsjS8fz2Xj15D2mrsaT9u, admin@seat.local, 1, 2015-01-30 00:02:37, 2015-01-30 00:02:37))

**Comment by eve-seat** [comment]
I am going to guess that the version of MySQL/MariaDB shipped with C7 has some requirements that are more strict. [this](https://github.com/eve-seat/seat/blob/master/app/database/migrations/2014_12_13_101533_AddLastLoginDateAndSource.php) migration introduced the field that it is complaining about which did not get a default value assigned.

I will log a new issue to test a C7 install and see what the pains are and what can be done to make it work flawlessly too.

**Comment by eve-seat** [comment]
I logged #334 to track the C7 testing.

**Comment by eve-seat** [comment]
@SandyVaJJ, we have a fix added in the dev branch now for this specific issue. Should land in the next point release.

**Comment by SandyVaJJ** [comment]
which database are you using mysql community or mariadb, according to yum search mysql-server there, it isnt on epel 7

**Comment by eve-seat** [comment]
I think C7 swapped out mysql in favor of mariadb. I am yet to do a full installation on C7 though, and that is what #334 is for.

**Comment by SandyVaJJ** [comment]
Well I finally got the server to work, I can't connect but I think that's my fault on not knowing apache and also installing the server on my laptop

**Comment by eve-seat** [comment]
Awesome. Will leave #334 open though to finish the C7 docs.

**Comment by SandyVaJJ** [comment]
ok cool
