### ISSUE TITLE
Test CentOS 7 installation and API update

### ISSUE THREAD

**Issue by eve-seat** [eve-seat/seat#334]
It would seem like a few things may need some massaging in order for SeAT to be happy on a Centos7 host. I think most of it may actually just be as a result of MariaDB. Test a fresh installation on C7 and make sure that a full API run is successful.

**Comment by eve-seat** [comment]
Got some docs up here: https://github.com/eve-seat/seat/blob/dev/docs/INSTALL_Centos7.md
Feedback please!

**Comment by Nutbolt52** [comment]
Looks good, and still love that asciicinema site! Only suggestion would be to make it a little more obvious that MySQL has 'changed names to' MariaDB. I know you say they are binary compatible, but for some of the less techy people installing SeAT they may get confused. 

IMO just add a sentence like: "In CentOS7 MySQL has been replaced with MariaDB, however the same commands you would use for MySQL work in MariaDB. "

**Comment by SandyVaJJ** [comment]
also a lot of the commands just replace MySQL with MariaDB

**Comment by eve-seat** [comment]
> also a lot of the commands just replace MySQL with MariaDB

Could you give examples?

**Comment by eve-seat** [comment]
Considering this done. Open a new issue if there are problems.
