### ISSUE TITLE
Error after adding ALL permissions to a usergroup

### ISSUE THREAD

**Issue by apfelqoo** [eve-seat/seat#344]
production.ERROR: exception 'ErrorException' with message 'unserialize(): Error at offset 257 of 255 bytes' in /var/www/seat/app/services/auth/SeatGuard.php:209

Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(8, 'unserialize(): ...', '/var/www/seat/a...', 209, Array)
#1 /var/www/seat/app/services/auth/SeatGuard.php(209): unserialize('a:9:{s:13:"asse...')
#2 [internal function]: App\Services\Auth\SeatGuard->isSuperUser()
#3 /var/www/seat/bootstrap/compiled.php(7776): call_user_func_array(Array, Array)
#4 /var/www/seat/bootstrap/compiled.php(3174): Illuminate\Support\Manager->__call('isSuperUser', Array)
#5 /var/www/seat/bootstrap/compiled.php(3174): Illuminate\Auth\AuthManager->isSuperUser()
#6 /var/www/seat/app/controllers/HomeController.php(55): Illuminate\Support\Facades\Facade::__callStatic('isSuperUser', Array)
#7 /var/www/seat/app/controllers/HomeController.php(55): Illuminate\Support\Facades\Auth::isSuperUser()
#8 [internal function]: HomeController->showIndex()
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#10 /var/www/seat/bootstrap/compiled.php(5437): Illuminate\Routing\Controller->callAction('showIndex', Array)
#11 /var/www/seat/bootstrap/compiled.php(5425): Illuminate\Routing\ControllerDispatcher->call(Object(HomeController), Object(Illuminate\Routing\Route), 'showIndex')
#12 /var/www/seat/bootstrap/compiled.php(4657): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'HomeController', 'showIndex')
#13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#14 /var/www/seat/bootstrap/compiled.php(4984): call_user_func_array(Object(Closure), Array)
#15 /var/www/seat/bootstrap/compiled.php(4682): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#16 /var/www/seat/bootstrap/compiled.php(4670): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#17 /var/www/seat/bootstrap/compiled.php(706): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#18 /var/www/seat/bootstrap/compiled.php(687): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#19 /var/www/seat/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/seat/bootstrap/compiled.php(1146): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#21 /var/www/seat/bootstrap/compiled.php(7311): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#22 /var/www/seat/bootstrap/compiled.php(7908): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#23 /var/www/seat/bootstrap/compiled.php(7855): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/seat/bootstrap/compiled.php(10898): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/seat/bootstrap/compiled.php(648): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#26 /var/www/seat/public/index.php(49): Illuminate\Foundation\Application->run()
#27 {main} [] []

**Comment by apfelqoo** [comment]
The permission field in seat_groups (SQL) will be truncated after 255 chars. If you are so stupid like me and add all permissions (incl. Superuser) to a group this will happen.

You can fix this if you (re)set the permissions in seat_groups

Defaults for a fresh install:

Administrators: a:1:{s:9:"superuser";s:1:"1";}
POS Managers: a:1:{s:11:"pos_manager";i:1;}
Wallet Managers: a:1:{s:14:"wallet_manager";i:1;}
Recruiters: a:1:{s:9:"recruiter";i:1;}
Asset Managers: a:2:{s:11:"pos_manager";i:1;s:13:"asset_manager";i:1;}
Contract Managers: a:1:{s:16:"contract_manager";i:1;}
Market Managers: a:1:{s:14:"market_manager";i:1;}
Key Manager: a:1:{s:11:"key_manager";i:1;}

**Comment by eve-seat** [comment]
Thanks for debugging this. Will add a migration to increase the field size.
