### ISSUE TITLE
[BUG] Saving Number Format with a space

### ISSUE THREAD

**Issue by Nutbolt52** [eve-seat/seat#345]
When saving the SeAT settings, if I set the Number Format to (space), it doesn't save and I get this error: Error! The thousand seperator field is required.

It saves with other formats for the thousand separator

**Comment by Nutbolt52** [comment]
To expand on this, I appear to be able to set the (space) seperator ok for my personal profile, it just struggles with the overall SeAT setting

**Comment by eve-seat** [comment]
Fixed in ba486738
