### ISSUE TITLE
[BUG] Pagination display on Notifications page not working

### ISSUE THREAD

**Issue by Nutbolt52** [eve-seat/seat#347]
When viewing all notifications at the bottom of the page the pagination doesn't display correctly.

1.) It doesn't calculate the total number of notifications (give us the option to delete a notification so this doesn't get silly?)

2.) When you change page it doesn't update the entries. See screenshot below

![Issue](http://i.nutbolt.eu/2015-02-17_09-35-10.png)

**Comment by eve-seat** [comment]
So the 1 to 50 of 50 entries is data tables telling you how many there are in the current view. Datatables has not idea of what is going on in the backend as this is purely client side.

**Comment by Nutbolt52** [comment]
This is completely pointless having it as its just giving false information :) 

FYI datatables does allow for server side shit. Which would give you accurate numbers etc... (but I wouldn't have a clue how to even start implementing it into SeAT).

**Comment by eve-seat** [comment]
Definitely not useless nor giving false information if you are filtering using the client side search on the top right. 

![d](http://i.imgur.com/rb4RsWp.png)
