### ISSUE TITLE
Bookmarks in a starbase hanger/container will result in a division by 0.

### ISSUE THREAD

**Issue by mglinski** [eve-seat/seat#353]
Put a single bookmark in any pos module and nothing else.
Load up corp assets.
Bookmarks have a 0.0 value for their volume
results in trying to find the % of used space for that item in the container, and divides by 0.

**Comment by apfelqoo** [comment]
Thank you very much for the time you spent with me (noob) to find this bug!

**Comment by eve-seat** [comment]
Stupid bookmark :P

**Comment by kunnis** [comment]
Ignore the e8c313f commit...

I also did a review of our usage of the / symbol in all blades, none seem to have any divide by zero problems that should pop up.

**Comment by eve-seat** [comment]
Fixed in #369
