### ISSUE TITLE
Should Corp APIs count towards "Key Ok"

### ISSUE THREAD

**Issue by kunnis** [eve-seat/seat#370]
On the corporation/member-tracking page, I only have the corp API key in my system, but the director that owns the API key is showing "Key Ok".  I think that in this case it should show "Key not Ok".  I can make this change if you're okay with it.

**Comment by Nutbolt52** [comment]
I personally think it shouldn't say the key is ok, because the directors key is in fact not ok, as the corp key doesn't show any private info about the director.

**Comment by eve-seat** [comment]
Yeah this is a valid point. Just not sure how to we going to distinguish cleanly :P

**Comment by LunarchildEU** [comment]
In ``getMemberTracking()`` the Controller joins ``account_apikeyinfo``, so it should consider all key types except for a Corporation key, so adding something around [Line 216](https://github.com/eve-seat/seat/blob/dev/app/controllers/CorporationController.php#L216) like that:
```
->where('ap.type', '!=', 'Corporation')
```
and it should perhaps consider the right keys.

**Comment by eve-seat** [comment]
@LunarchildEU wont adding this where actually exclude that character from the corporation keys, instead of showing the character as a notOK key? May have to case this one.

**Comment by warlof** [comment]
I think know if we've a director key for a corp isn't usefull...

If you've access to corp part, it's because somebody has add a corp key.
And the only guy who could want to know if he has all corp key his install should have is admin and he can do it by accessing the global api key list and sort by key type.

Instead i have miss hunderstand something here.

**Comment by kunnis** [comment]
I think it showing "Key Ok" for a director key is actually slightly detrimental, because you think you have a character key when you really don't.  And director level spies and all of that, you should know when you don't have an api for someone.
