### ISSUE TITLE
Avatar Quality Issue (I missed one)

### ISSUE THREAD

**Issue by Nutbolt52** [eve-seat/seat#376]
Logging this so someone can do it if I never get round to it, but I noticed on the character view the toons on the same api key avatar images are still lower quality. They need changing to _64 image server images.

**Comment by mglinski** [comment]
Images now are lazy loaded based on the browser's current viewport and a flag representing a "retina" or hidpi screen. If you are browsing on a device that is hidpi, it will detect that and load x2 images instead of x1 images.

**Comment by Nutbolt52** [comment]
Yup, true, had forgotton (but seat is much faster now on those bigger pages!). However the image is still shitty quality. It grabs the x32 version from CCPs image servers, then scales it to x64 resolution. It should just grab the x64 res image from CCP. I'm sure peoples bandwidth can cope with the slightly bigger picture :)

**Comment by mglinski** [comment]
![](http://cl.ly/image/3139202n443a)

**Comment by Nutbolt52** [comment]
In #354 I went through and increased the quality to pull from ccp to 64x64, 32 just looks crap, no matter how small the image is. 

As for your screenshot, err, mine is displaying 64px lol. Which means the 2 avatars actually touch each other. 

I think 64px is the right size, but would need some padding or something. So 2 issues here lol. Increase quality grabbed from CCP, and work out why mine displays bigger than yours (im running 0.14)
