### ISSUE TITLE
Assets view - Table headings randomly inserted into assets list

### ISSUE THREAD

**Issue by Nutbolt52** [eve-seat/seat#378]
Running latest version (0.14). I don't know if this was an issue before or not. 

When looking at the assets list for a character it seems to be inserting the table headings randomly into the list. An example: 

![](http://i.nutbolt.eu/2015-03-05_20-56-02.png)

**Comment by eve-seat** [comment]
Always been like this. Its a side effect of the way the assets are split into 2 columns.

**Comment by Nutbolt52** [comment]
Has it been deemed unfixable, or just hasn't had the time to look into it?
