### ISSUE TITLE
API Keys not updating

### ISSUE THREAD

**Issue by freedenizen** [eve-seat/seat#379]
I noticed that some keys were not updating although many others were. There was no problem with the keys themselves (manual checks confirmed that) I moved on and ran the following in tinker to mimic: https://github.com/eve-seat/seat/blob/master/app/commands/scheduled/EveCharacterUpdater.php#L99
```
foreach (\SeatKey::where('isOk', '=', 1)->get() as $key) {
  if ($key->keyID == [KEY_NOT_RUNNING]){
    echo "checking access...";
  }
  $access = \Seat\EveApi\BaseApi::determineAccess($key->keyID);
  if (!isset($access['type'])) {
      continue;
  }
  if ($access['type'] == 'Character') {
    if ($key->keyID == [KEY_NOT_RUNNING]){
      echo "found";
    }
  }
}
```
This resulted in the following error:
```
PHP Fatal error:  Uncaught exception 'Pheal\Exceptions\APIException' with message 'Authentication failure.' in /var/www/seat/vendor/3rdpartyeve/phealng/lib/Pheal/Core/Result.php:95
Stack trace:
#0 /var/www/seat/vendor/3rdpartyeve/phealng/lib/Pheal/Pheal.php(294): Pheal\Core\Result->__construct(Object(SimpleXMLElement))
#1 /var/www/seat/vendor/3rdpartyeve/phealng/lib/Pheal/Pheal.php(110): Pheal\Pheal->requestXml('account', 'APIKeyInfo', Array)
#2 /var/www/seat/app/eveapi/account/AccountAPIKeyInfo.php(53): Pheal\Pheal->__call('APIKeyInfo', Array)
#3 /var/www/seat/app/eveapi/account/AccountAPIKeyInfo.php(53): Pheal\Pheal->APIKeyInfo()
#4 /var/www/seat/app/eveapi/BaseAPI.php(380): Seat\EveApi\Account\APIKeyInfo::Update('[OTHERKEY]', 'xxxxxxx')
#5 /var/www/seat/vendor/d11wtq/boris/lib/Boris/EvalWorker.php(152) : eval()'d code(5): Seat\EveApi\BaseApi::determineAccess('[OTHERKEY]')
#6 /var/www/seat/vendor/d11wtq/boris/lib/Boris/EvalWorker.php(152): eval()
#7 /var/www/seat/vendor/d11wtq/boris/lib/Boris/Boris.php(175): Boris\EvalW in /var/www/seat/vendor/3rdpartyeve/phealng/lib/Pheal/Core/Result.php on line 95
```
Once I removed the key referenced above, testing worked fine, and all keys began to process cleanly. I am guessing that we need to catch the exception here: https://github.com/eve-seat/seat/blob/master/app/commands/scheduled/EveCharacterUpdater.php#L106

**Comment by eve-seat** [comment]
I think this actually goes all the way back to [this](https://github.com/eve-seat/seat/blob/master/app/eveapi/account/AccountAPIKeyInfo.php#L65) `case` block. From the stack trace I am reading "`Authentication failure.`" which indicates that it may be a error from the [error list](https://api.eveonline.com/Eve/ErrorList.xml.aspx) that we are not catering for, therefore [throwing an exception](https://github.com/eve-seat/seat/blob/master/app/eveapi/account/AccountAPIKeyInfo.php#L133). This I guess kills the flow and should be handled differently.

**Comment by eve-seat** [comment]
Pushed 92cee22ca0 to try and fix this. Testing my install now. If all good I'll push a 14.1 with this in.
