### ISSUE TITLE
Permissions Revision

### ISSUE THREAD

**Issue by eve-seat** [eve-seat/seat#388]
This ticket is to track the progress and discuss the permissions revision that is being done.

A few outcomes of this should be:
- Decouple the currently abused _recruiter_ role that is practically used for everything.
- Make permissions as granular as possible. Most actions will have their own permission. Ultimately, permissions should be grouped and group access should be given to users.
- Remove unnecessary checks for `isSuperUser()` as these users inherit all permissions.
- Ship some default groups with sane default permissions. 
- Documentation for permissions. This needs to explain key ownership, corporation affiliation by key as well as what each and every permission gives access to.
- Minor UI enhancements for the user/groups management so make the management of them make more sense.

Please keep discussions in this ticket strictly on topic.

**Comment by eve-seat** [comment]
Have started with settingcontroller permissions. Here is a section out of my notes of what I have so far:

```
 -------------------------------------------------------------------------------------------------------
|  Source Controller    | Function                              | Permission Name                       |
|---------------------------------------------------------------|---------------------------------------|
| ApiKeyController      | View All API Keys                     | api_key_list                          |
| ApiKeyController      | View API Detail                       | api_key_detail                        |
| ApiKeyController      | Update Key Info                       | api_key_update                        |
| ApiKeyController      | Enable / Disable API Keys             | api_key_enable_disable                |
| ApiKeyController      | Delete API Keys                       | api_key_delete                        |
| ApiKeyController      | Mass remove bans and enable keys      | api_key_mass_enable                   |
| ApiKeyController      | See All People Groups                 | people_groups_view_all                |
| ApiKeyController      | Create People Groups                  | people_groups_create                  |
| ApiKeyController      | Edit People Groups (add/remove)       | people_groups_edit                    |
| ApiKeyController      | Transfer API Key Owner                | Super Users                           |
|---------------------------------------------------------------|---------------------------------------|
| CharacterController   | List all characters                   | character_list_all                    |
| CharacterController   | View all characters summaries         | character_view_summary                |
| CharacterController   | View all characters skills            | character_skills                      |
| CharacterController   | View all characters wallet journal    | character_wallet_journal              |
| CharacterController   | View all characters wallet transactions | character_wallet_transactions       |
| CharacterController   | View all characters mail              | character_mail                        |
| CharacterController   | View all characters notifications     | character_notifications               |
| CharacterController   | View all characters assets            | character_assets                      |
| CharacterController   | View all characters contacts          | character_contacts                    |
| CharacterController   | View all characters contracts         | character_contracts                   |
| CharacterController   | View all characters market orders     | character_market_orders               |
| CharacterController   | View all characters calendar          | character_calendar                    |
| CharacterController   | View all characters standings         | character_standings                   |
| CharacterController   | View all characters killmails         | character_killmails                   |
| CharacterController   | View all characters research agents   | character_research_agents             |
| CharacterController   | View all characters PI                | character_pi                          |
| CharacterController   | View all characters industry          | character_industry                    |
|---------------------------------------------------------------|---------------------------------------|
| CorporationController | View all corporations                 | corporation_list_all                  |
| CorporationController | View corporation journal              | corporation_wallet_journal            |
| CorporationController | View corporation transactions         | corporation_wallet_transactions       |
| CorporationController | View corporation member tracking      | corporation_member_tracking           |
| CorporationController | View corporation assets               | corporation_assets                    |
| CorporationController | View corporation contracts            | corporation_contracts                 |
| CorporationController | View corporation starbases            | corporation_star_bases                |
| CorporationController | View corporation ledger               | corporation_ledger                    |
| CorporationController | View corporation member security      | corporation_member_security           |
| CorporationController | View corporation market orders        | corporation_market_orders             |
| CorporationController | View corporation member standings     | corporation_member_standings          |
| CorporationController | View corporation killmails            | corporation_killmails                 |
| CorporationController | View corporation Industry Jobs        | corporation_industry                  |
| CorporationController | View corporation Pocos                | corporation_poco                      |
|---------------------------------------------------------------|---------------------------------------|
| DashboardController   | Search All Characters                 | search_all_characters                 |
| DashboardController   | Search All Character Assets           | search_all_character_assets           |
| DashboardController   | Search All Character Contacts         | search_all_character_contact_lists    |
| DashboardController   | Search All Character Mail             | search_all_character_mail             |
| DashboardController   | Search All Character Standings        | search_all_character_standings        |
| DashboardController   | Search All Corporation Assets         | search_all_corporation_assets         |
| DashboardController   | Search All Corporation Standings      | search_all_corporation_standings      |
|---------------------------------------------------------------|---------------------------------------|
| MailController        | View all mail subjects                | mail_all_subjects                     |
| MailController        | View all mail bodies                  | mail_all_bodies                       |
 -------------------------------------------------------------------------------------------------------
```

Should see some actual code say around Friday / Saturday. The idea will be to have these granular permissions assigned to groups and users added to the groups.

**Comment by warlof** [comment]
Member security and tracking shouldn't have same permission ?

About view, i think the more evolutive is to display "rules" in an array with one rule per line and a radio yes/no and a (i) info toolbox inside which putting rule description (for the create/edit group view)

I think display group member in each group view could be usefull too (and a quick "remove user from group") button in order to prevent user navigation.

For core, maybe adding a permission which allow a ceo to edit api required access mask (and so, make a default setting access mask and a corp one which is editable by a corp member with enough power)

Still about permission, maybe corp should have access to their own group rules instead of a global group.

**Comment by eve-seat** [comment]
> Member security and tracking shouldn't have same permission ?

You will put these in a group and assign accordingly if you so wish. It is important to make this as granular as this, as you may believe these should be the same, but trust me, people have so many different views, its best to just leave it up to them.

**Comment by eve-seat** [comment]
Commit b57d77d096 has been pushed. This should give a pretty ok idea of what it will be like from a controller/view permissions perspective.

**Comment by eve-seat** [comment]
Do not update production systems to the latest `dev` branch now as all the permissions will be broken. Basically, only superusers will really be able to use it in its current state. :)

**Comment by eve-seat** [comment]
6cafeb7be2f5 introduces a small re factor for the majority of the controllers' ACL checking. A few filters have been added and are bound to via the Controller `__construct()`'s.

Have also started a security logger event to help with debugging and what not. This event can be listened on later in a command line tail tool.

**Comment by eve-seat** [comment]
Ok. I think dev is in a workable state again since 6cafeb7be2 , 8584135e8a09 , d58ed7973867 and 13f6238301d673c9125a282. Its testing time!

Reseed the permissions with `php artisan db:seed --class=SeatPermissionsSeeder` and resetup/test permissions!

**Comment by Zumochi** [comment]
Some first notes:

- The "Update Group Permissions" window can and should be larger. May I suggest changing it to a list of checkboxes too? Having to go through such a small scrolldown box again and again for every permission someone would like to add isn't very nice. Then, for example, if you hover over a permission for half a second or something, you get to view the longer description.
- Currently, opening the "Permissions details" window looks aesthetically nice but is unpractical.

I also think the permissions are still lacking options:
- The permissions are misleading:
  - First, the descriptions imply you can "View _all_ [characters|corporations] `permission`":
  - Users can currently _only_ view information about API keys _they_ added, even though they have the permission to view corporation star bases from all corporations (for example).
  - At the same time, someone that can view API key details, can *ALSO* view _keys_ and vcodes from _all_ other users, including himself. This way, they can just copy those and enter them in their own account, effectively taking control of the entry and allowing to view all information etcetera.

**Comment by eve-seat** [comment]
> Some first notes:
> 
> The "Update Group Permissions" window can and should be larger. 

Why?

>May I suggest changing it to a list of checkboxes too? Having to go through such a small scrolldown box again and again for every permission someone would like to add isn't very nice. Then, for example, if you hover over a permission for half a second or something, you get to view the longer description.

At the moment you get to type to filter. Just like you would end up doing with something like ctrl+f for a large list such as this.
> Currently, opening the "Permissions details" window looks aesthetically nice but is unpractical.

Any suggestion? This comment as it is holds no value. Is this tied to the previous?

> I also think the permissions are still lacking options:
> 
> The permissions are misleading:
> First, the descriptions imply you can "View all [characters|corporations] permission":

This is the intent. More descriptions and work is still coming.

> Users can currently only view information about API keys they added, even though they have the permission to view corporation star bases from all corporations (for example).

This is actually useful so I can check it out. With some more details around key ownership and affiliation things should become more clear though. 

> At the same time, someone that can view API key details, can ALSO view keys and vcodes from all other users, including himself. This way, they can just copy those and enter them in their own account, effectively taking control of the entry and allowing to view all information etcetera.

Correct. Hence why you will not just assign anyone any permission without reading.

**Comment by Zumochi** [comment]
>Why?
It takes about 1/3 of the entire room of the container... Plus having a list like this doesn't 
![27ac13d122 1](https://cloud.githubusercontent.com/assets/5372678/6690195/50aca540-ccbf-11e4-8cae-e91619906ada.png) in my opinion not very nice. If you add a lot of permissions you end up having to scroll every time after you add an permission as well.
May I suggest categorizing permissions instead?

>At the moment you get to type to filter. Just like you would end up doing with something like ctrl+f for a large list such as this.
Fair enough.

>Any suggestion? This comment as it is holds no value. Is this tied to the previous?
Is indeed tied to the previous. If you make the list box wider, you can easily fit short descriptions like these next to the permission itself.

>This is the intent. More descriptions and work is still coming.
Looking forward to them :grin:

>This is actually useful so I can check it out. With some more details around key ownership and affiliation things should become more clear though.
What do you mean exactly?

>Correct. Hence why you will not just assign anyone any permission without reading.
Then what are you supposed to do with recruiters? Allow them to view _every_ key in an alliance? I stand by my comment and think this should optionally be tied to one (or a group of) corporation(s) and/or alliance(s) for a user(group).

**Comment by LunarchildEU** [comment]
Welcome to the dev branch. :smile:

This major change may breaks certain things or is a bit flaky, but as far I understood there is changes and improvements incoming.

Just a thought about that 'Group Permissions' UI thing:
![image](https://cloud.githubusercontent.com/assets/2454083/6691800/002cd5ea-ccc9-11e4-8362-b0d60b066fb9.png)

The problem is, that after adding a large selection of permissions that do not fit the screen it opens the search bar above the first item of the input box.

Don't know if that is feasible, wanted to leave some feedback.

**Comment by warlof** [comment]
Still think that an array with on rule per line and yes/no swither are better ^^
May eventually display the list in 4 or 6 columns.

**Comment by eve-seat** [comment]
Mocking the UI is the easy part and can be changed. I am more concerned about the actual permissions.

**Comment by Zumochi** [comment]
@eve-seat do you have a plan what is going to be changed more about the permissions?

**Comment by eve-seat** [comment]
At the moment I want to add customized corp affiliations (so you can delegate access to corp info people don't have api keys for), as well as a similar thing for api keys for character info. There was something else I had in mind but I forget now.

**Comment by warlof** [comment]
Does it possible to allow access to corp's member to an account which is not in the same corp too ? In particular for skills ?

**Comment by ccatlett1984** [comment]
I agree, we need to allow a role on an “instance” level, that can see the skills of all members of corps on that instance. This will help alliance FC’s to determine what ships members can fly.






Sent from Windows Mail





From: Warlof Tutsimo
Sent: ‎Thursday‎, ‎March‎ ‎19‎, ‎2015 ‎8‎:‎00‎ ‎AM
To: eve-seat/seat





Does it possible to allow access to corp's member to an account which is not in the same corp too ? In particular for skills ?

**Comment by jrwr** [comment]
I'm using this on a alliance level, it would be nice to be able to limit people to just being able to see stuff to their corp, like a CEO of Corp A being able just to see corp mates assets, but if we define, being able to see skill training of everyone

**Comment by eve-seat** [comment]
Bumping this back up. This is going to go to master soon™, and then the 0.x branch will go into a feature freeze so that work on 1.x can be more focussed.

**Comment by emrysalf** [comment]
I have run into an issue which is about how the "recruiter" can see all apis of all corps and all users.. How can I limit it to just their corp users..?

**Comment by eve-seat** [comment]
@emrysalf to be honest, this will probably never land into the stable branch of SeAT 0.x. A ton of work is going into SeAT 1.x [here](https://github.com/eveseat/seat) (and its dependent repos) which has a ground up rewrite of the original permissions system. If you feel like testing that, there is a install guid in the 1.x WIKI here: https://github.com/eveseat/seat/wiki
