### ISSUE TITLE
Error in exception handler / Error 500

### ISSUE THREAD

**Issue by Soolarize** [eve-seat/seat#390]
Hi there, 

My SeAT does not seem to be working anymore after two full weeks of perfect use. 

I've installed it on a Debian 7 VPS. 

This morning one of my corpmate told me that our TeamSpeak 3 server was done. I logged in to the server using my Mac terminal, using the root command, restarted the TeamSpeak server, all good. But since then I can't access SeAT anymore: on Safari I have the "Error in exception handler." message while Chrome lets me land on the login/password screen but gives me an error 500. Did I break something on my VPS by restarting TeamSpeak?

**Comment by Nutbolt52** [comment]
If possible (i.e. won't affect other services), just restart the VPS to clear up any potential issues which might be hiding. Then we can take it from there, although I suggest joining the IRC channel (#wcs-pub), much faster help that way.

**Comment by Soolarize** [comment]
Hi nutbolt52, 

Well my lack of skills in administrating the VPS will kill me some day. I've restarted everything and SeAT seems back on track now. Thanks for the advice!

**Comment by Nutbolt52** [comment]
Never underestimate the power of turning it off and on again :) 

Feel free to mark this issue as closed, cheers.
