### ISSUE TITLE
SMTP trouble ??????

### ISSUE THREAD

**Issue by Tyrionestemaire** [eve-seat/seat#393]
SO im installing seat on centos 7. I have Seat working on a local level, but can not get the emails to send.
here the log
[2015-05-26 21:07:55] production.ERROR: exception 'Swift_TransportException' with message 'Connection could not be established with host mail.drunk-in-eve.com [Connection refused #111]' in /var/www/seat/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:265
Stack trace:
#0 /var/www/seat/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(62): Swift_Transport_StreamBuffer->_establishSocketConnection()
#1 /var/www/seat/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(113): Swift_Transport_StreamBuffer->initialize(Array)
#2 /var/www/seat/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(307): Swift_Mailer->send(Object(Swift_Message), Array)
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(134): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#5 /var/www/seat/bootstrap/compiled.php(3180): Illuminate\Mail\Mailer->send('emails.auth.reg...', Array, Object(Closure))
#6 /var/www/seat/app/controllers/RegisterController.php(91): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#7 /var/www/seat/app/controllers/RegisterController.php(91): Illuminate\Support\Facades\Mail::send('emails.auth.reg...', Array, Object(Closure))
#8 [internal function]: RegisterController->postNew()
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#10 /var/www/seat/bootstrap/compiled.php(5437): Illuminate\Routing\Controller->callAction('postNew', Array)
#11 /var/www/seat/bootstrap/compiled.php(5425): Illuminate\Routing\ControllerDispatcher->call(Object(RegisterController), Object(Illuminate\Routing\Route), 'postNew')
#12 /var/www/seat/bootstrap/compiled.php(4657): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'RegisterControl...', 'postNew')
#13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#14 /var/www/seat/bootstrap/compiled.php(4984): call_user_func_array(Object(Closure), Array)
#15 /var/www/seat/bootstrap/compiled.php(4682): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#16 /var/www/seat/bootstrap/compiled.php(4670): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#17 /var/www/seat/bootstrap/compiled.php(706): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#18 /var/www/seat/bootstrap/compiled.php(687): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#19 /var/www/seat/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/seat/bootstrap/compiled.php(1146): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#21 /var/www/seat/bootstrap/compiled.php(7311): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#22 /var/www/seat/bootstrap/compiled.php(7908): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#23 /var/www/seat/bootstrap/compiled.php(7855): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/seat/bootstrap/compiled.php(10898): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/seat/bootstrap/compiled.php(648): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#26 /var/www/seat/public/index.php(49): Illuminate\Foundation\Application->run()
#27 {main} [] []
and smtp setting
hostname: mail.********.com
username:**********
password:*********
smtp port: 25
smpt encryption: tls

**Comment by Tyrionestemaire** [comment]
and the username and password are correct

**Comment by LunarchildEU** [comment]
Hi,

that 'Connection could not be established with host
mail.drunk-in-eve.com [Connection
refused #111 <https://github.com/eve-seat/seat/issues/111>]' - sounds like
something mailserver / firewall related may is odd.

If you can telnet to it from your system, you may need to try a different
setting for the smtp encryption.

Regards

2015-05-26 23:17 GMT+02:00 Tyrionestemaire <notifications@github.com>:

**Comment by eve-seat** [comment]
Error is obviously connection related:

> 'Connection could not be established with host mail.drunk-in-eve.com [Connection refused #111]'

Seems like the mailserver is up though. Can you recheck if you still have problems?

**Comment by Tyrionestemaire** [comment]
I have got this issue resolved.
