### ISSUE TITLE
Group Permissions

### ISSUE THREAD

**Issue by Tyrionestemaire** [eve-seat/seat#394]
Just wondering why my group permissions look like this http://prntscr.com/7ax2kn
and not like this https://cloud.githubusercontent.com/assets/5372678/6690195/50aca540-ccbf-11e4-8cae-e91619906ada.png

**Comment by LunarchildEU** [comment]
That is one of the current new and tested features of dev branch (where new features are being tested before integration into the main tree) as per 
#388 (iirc)
