### ISSUE TITLE
long queue times?

### ISSUE THREAD

**Issue by Tyrionestemaire** [eve-seat/seat#395]
http://prntscr.com/7b9f66

just dont understand the queues. are the normally this long for the rest?

http://prntscr.com/7b9fr8

**Comment by LunarchildEU** [comment]
My gut tells me something is odd with your installation, that queue cleanup
task should be checking every 30mins if there are jobs older than 1hour
stuck in the queue and error them all out.

Even if you run it at a decent hosted virtual server it should not take
that long for one queued job to complete.

A good starting point may be the laravel.log in 'app/storage/logs', there
could be some insights what is going wrong.

2015-05-30 23:15 GMT+02:00 Tyrionestemaire <notifications@github.com>:

**Comment by SauerRam** [comment]
I'm having the same Problem. Running 2 instanzes of seat, one for testing, one more produktional.
every two of them show  
"0 Jobs in the Redis Queue, with a Redis status of: OK"
"Current Working Jobs: No Working Jobs, but there are jobs in the queue. Are the workers started?"

sipervisorctl tells me my 8 workers are Running. Redis says the same.

```
#/src/seat/artisan seat:queue-status
Redis reports 0 jobs in the queue (queues:default)
The database reports 35 queued jobs
[!] The redis & db queued counts are not the same. This is not always a bad thing
The database reports 17 done jobs
The database reports 0 error jobs
The database reports 0 working jobs
root@v22013021527310404:~#
```

haven't found any error's till now. where should I look for?

**Comment by warlof** [comment]
You need two instances of redis and supervisord
Le 8 juin 2015 15:06, SauerRam <notifications@github.com> a écrit :I'm having the same Problem. Running 2 instanzes of seat, one for testing, one more produktional.
every two of them show
"0 Jobs in the Redis Queue, with a Redis status of: OK"
"Current Working Jobs: No Working Jobs, but there are jobs in the queue. Are the workers started?"

sipervisorctl tells me my 8 workers are Running. Redis says the same.

#/src/seat/artisan seat:queue-status
Redis reports 0 jobs in the queue (queues:default)
The database reports 35 queued jobs
[!] The redis & db queued counts are not the same. This is not always a bad thing
The database reports 17 done jobs
The database reports 0 error jobs
The database reports 0 working jobs
root@v22013021527310404:~#


haven't found any error's till now. where should I look for?

**Comment by SauerRam** [comment]
supervisord handles every worker you give him a config for, and redis are two different instances.

**Comment by warlof** [comment]
Does both of your config file are correctly configured ? In particulare redis port.
Do you have one cron task per seat instance ?
Le 8 juin 2015 16:06, SauerRam <notifications@github.com> a écrit :supervisord handles every worker you give him a config for, and redis are two different instances.

**Comment by SauerRam** [comment]
Yes and Yes. Notized this already before setting up the second instance. Some of the Jobs get done, most are requeued, and get done 1-2 once in a while (every ~2h).
Tried to solve this by changing the environment for the clone, with getting most recent redit, pip, python, php, but issue with unnormal job duration is still there

**Comment by warlof** [comment]
how many supervisor process do you have foreach of its instance ?

**Comment by SauerRam** [comment]
4 each, 8 in total, so 4 per seat instance

**Comment by LunarchildEU** [comment]
Question is: Do the 2 instances share anything else, except the webserver and being on the same host.

Supervisor in this case does not look like the problem, do you use different Redis DBs for each?

**Comment by SauerRam** [comment]
I assume the fact it worked the same way with only one instance pushes that choice apart as a reason, but can you tell me where the redis DBs are configured? Maybe I get to some trustworthy error reason from there. Only thing i can imagine atm is the one with :

     The redis & db queued counts are not the same. This is not always a bad thing

**Comment by LunarchildEU** [comment]
In [`app/config/database.php` around Line 142](https://github.com/eve-seat/seat/blob/master/app/config/database.php#L142) the 0 should be changed

**Comment by warlof** [comment]
http://chrislaskey.com/blog/342/running-multiple-redis-instances-on-the-same-server/
Le 9 juin 2015 09:12, SauerRam <notifications@github.com> a écrit :I assume the fact it worked the same way with only one instance pushes that choice apart as a reason, but can you tell me where the redis DBs are configured? Maybe I get to some trustworthy error reason from there. Only thing i can imagine atm is the one with :

 The redis & db queued counts are not the same. This is not always a bad thing

**Comment by warlof** [comment]
For n seat instance you should have :
n cron task
n redis instance
n supervisor instance
n sql db
n seat clone
Le 9 juin 2015 10:14, "Alexander A." <notifications@github.com> a écrit :In app/config/database.php around Line 142 the 0 should be changed

**Comment by SauerRam** [comment]
Le 9 juin 2015 10:14, "Alexander A." <notifications@github.com> a écrit :In app/config/database.php around Line 142 the 0 should be changed

--> seems to solve my issue for both instances, pulling the jobs out of queue now as expected

**Comment by SauerRam** [comment]
If this is something one of the developers wants to include into settings, please close it, for me changing the value from 0 to 1 for 1 instance worked for both instances (so 1st is set to 0, 2nd to 1).
Watched my Queue closely the last 5 days and couldn't reveal any issues, so for my case CLOSED

**Comment by eve-seat** [comment]
Multiple instances on the same host is not really something that is officially supported atm. I will tag this as an enhancement and look at having some configs prepared so that may in fact be possible. Thanks to all for the help :)
