### ISSUE TITLE
Corp contracts not loading...

### ISSUE THREAD

**Issue by davidjeddy** [eve-seat/seat#404]
"...Sorry! Something went wrong.
Chances are the site administrator will be super happy if you told him this, along with what you last did to get here. That way they could have a look at log files and try and fix it...."

accessed via {root}/corporation/contracts/98118130

Three different corp. keys attempted, all the with the same result.

**Comment by eve-seat** [comment]
Could you check out what is in `app/storage/logs/laravel.log` when this happens?

**Comment by eve-seat** [comment]
Any update?

**Comment by schealex** [comment]
this is most likely a memory error, try increasing php memory limits

**Comment by eve-seat** [comment]
Please re-open once you have some log extracts.
