### ISSUE TITLE
[Enhancement] Silo status in starbase overview + potential ISK generation

### ISSUE THREAD

**Issue by plantronic** [eve-seat/seat#405]
I am managing a semi large quantity of starbases and it would be nice to have the top list of starbases show silo fill status and moongoo variant under the fuel bar.
On top of that it would be nice if market data could be used to calculate isk/hr from goo price - running fuelcost and shown somewhere there aswell.

**Comment by ChrisKing517** [comment]
This would be much more helpful and looks fairly easy to do, since its basically a copy+paste of code

**Comment by Str1k3r2k4** [comment]
thumps Up and Bump ! Need it also ;)
