### ISSUE TITLE
High CPU-load by the queues

### ISSUE THREAD

**Issue by MaxRink** [eve-seat/seat#411]
laravel creates a high load for the cpu.
this is caused by queue:listen.

any way how to avoid this besides the implementation of queue:work --daemon over queue:listen (would require a newer lavarel-version)?

**Comment by eve-seat** [comment]
Probably not. Unless you can profile and point out which worker is hogging the CPU.
FWIW - SeAT will be moving to Laravel 5.1 LTS in the new future.

**Comment by MaxRink** [comment]
looking forward to that.
