### ISSUE TITLE
Some dates are inaccurate

### ISSUE THREAD

**Issue by MaxRink** [eve-seat/seat#412]
some dates are not correct. for example the remaining time till the skillqueue ends
![1](https://cloud.githubusercontent.com/assets/4894735/9419112/398535ce-4859-11e5-9f45-6d11d0787ed8.PNG)
the API of that char is still valid and its still skilling

**Comment by eve-seat** [comment]
A few things.
All dates are sourced from the XML API. As  you know, these may have a cached until time.
SeAT tries to make no predictions on the time, so if the actual value in the database has not been updated recently, then it will stay as it is.
Are you sure there are no banned calls? The workers are fine? Have you checked the logs for the specific calls? What about the XML cache on disk? Have you verified that the database table/column has been updated?

**Comment by LunarchildEU** [comment]
Sorry to say that, but if you use HHVM there is an upstream issue with the Carbon dependency of Laravel, this should be no defect within SeAT or XML API.
Found on [Travis](https://travis-ci.org/briannesbitt/Carbon) that there are some [Unit tests failing](https://github.com/briannesbitt/Carbon/blob/master/tests/DiffTest.php) for this specific thing.

**Comment by MaxRink** [comment]
so i have to wait for a fix by them, k

**Comment by eve-seat** [comment]
Can you confirm that it is in fact HHVM causing the problem here?

**Comment by MaxRink** [comment]
im running HHVM + nginx, yes
