### ISSUE TITLE
Additional Custom Field in User

### ISSUE THREAD

**Issue by schealex** [eve-seat/seat#413]
Hello Guys,

we need a custom field for the User which sould also be avail at registration.
is that possible and maybe it could be implemented in seat in general?

Regards

**Comment by eve-seat** [comment]
Hey,

Which custom field is this?

**Comment by schealex** [comment]
didn't check the code. thanks to you using a clear code and laravel mvc it took like 5 mins :)

**Comment by eve-seat** [comment]
:)
