### ISSUE TITLE
Installed on Raspberry Pi B+ with Debian OS

### ISSUE THREAD

**Issue by Str1k3r2k4** [eve-seat/seat#416]
Hy ther,

first sry for my english skills im from germany and the lang eng. ist not my best language.

I try to installing on raspberry pi b+ with debian OS.
All good and its running, im take from my desktop PC with putty a connection to the Terminal and install all the things from your guid.

Now i tryed over network to surf on the page and its running but now comes the issue 

The page dont have some Layout or Template !!! Only white color and login Screen, after login with admin the new page is loading but also white with all menü. Now try to klick somthing but no reaction, only loading the same page.

sry for my language skills

**Comment by eve-seat** [comment]
Hey,

With the info given, I can only assume that something may be up with the configuration of your webserver. Try looking at the apache logs (assuming that's the web server you are using) as well as the Laravel log in `app/storage/logs/laravel.log`.

HTH

**Comment by Str1k3r2k4** [comment]
[2015-09-20 13:11:53] production.ERROR: exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user$
Stack trace:
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(47): PDO->__construct('mysql:host$
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(20): Illuminate\Database\Con$
#2 /var/www/seat/bootstrap/compiled.php(7208): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 /var/www/seat/bootstrap/compiled.php(7203): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Arra$
#4 /var/www/seat/bootstrap/compiled.php(7127): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#5 /var/www/seat/bootstrap/compiled.php(7101): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 /var/www/seat/bootstrap/compiled.php(6982): Illuminate\Database\DatabaseManager->connection(NULL)
#7 /var/www/seat/bootstrap/compiled.php(6969): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#8 /var/www/seat/bootstrap/compiled.php(6577): Illuminate\Database\Eloquent\Model->getConnection()
#9 /var/www/seat/bootstrap/compiled.php(6546): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php(87): Illuminate\Database\Eloquent\Mo$
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(346): Illuminate\Auth\EloquentUserProvider->retriev$
#12 [internal function]: Illuminate\Auth\Guard->attempt(Array, false)
#13 /var/www/seat/bootstrap/compiled.php(7776): call_user_func_array(Array, Array)
#14 /var/www/seat/bootstrap/compiled.php(3178): Illuminate\Support\Manager->__call('attempt', Array)
#15 /var/www/seat/bootstrap/compiled.php(3178): Illuminate\Auth\AuthManager->attempt(Array, false)
#16 /var/www/seat/app/controllers/SessionController.php(105): Illuminate\Support\Facades\Facade::__callStatic('attempt', Arr$
#17 /var/www/seat/app/controllers/SessionController.php(105): Illuminate\Support\Facades\Auth::attempt(Array, false)
#18 [internal function]: SessionController->postSignIn()
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#20 /var/www/seat/bootstrap/compiled.php(5437): Illuminate\Routing\Controller->callAction('postSignIn', Array)
#21 /var/www/seat/bootstrap/compiled.php(5425): Illuminate\Routing\ControllerDispatcher->call(Object(SessionController), Obj$
#22 /var/www/seat/bootstrap/compiled.php(4657): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\$
#23 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#24 /var/www/seat/bootstrap/compiled.php(4984): call_user_func_array(Object(Closure), Array)
#25 /var/www/seat/bootstrap/compiled.php(4682): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#26 /var/www/seat/bootstrap/compiled.php(4670): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 /var/www/seat/bootstrap/compiled.php(706): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 /var/www/seat/bootstrap/compiled.php(687): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#29 /var/www/seat/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(O$
#30 /var/www/seat/bootstrap/compiled.php(1146): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), $
#31 /var/www/seat/bootstrap/compiled.php(7311): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#32 /var/www/seat/bootstrap/compiled.php(7908): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, tr$
#33 /var/www/seat/bootstrap/compiled.php(7855): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#34 /var/www/seat/bootstrap/compiled.php(10941): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#35 /var/www/seat/bootstrap/compiled.php(648): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#36 /var/www/seat/public/index.php(49): Illuminate\Foundation\Application->run()
#37 /var/www/seat/server.php(19): require_once('/var/www/seat/p...')
#38 {main} [] []

**Comment by Str1k3r2k4** [comment]
but i fix the problem with sql connection

**Comment by Str1k3r2k4** [comment]
i have two screenschoots for the issue : 

The Login Page -> http://postimg.org/image/q3mf8pki9/
The Admin Page -> http://postimg.org/image/gtzxbfvgf/

Also the time too load Login is very Long, about 5 Min. but i think this is in depend of the Performance from Raspberry Pi.

**Comment by eve-seat** [comment]
From the screenshots it looks like your webserver may not have been correctly set up as I suspected. Could you double check your configs with the guide and ensure that the web root is to the `public/`folder?

**Comment by Str1k3r2k4** [comment]
Hy ther, its work for the moment.
I have check the 001-seat.conf and chance the Serveralias to raspberrypi.
Now is loading ...

thank you & donation in Game is coming up in next week 1 Bil IsK

**Comment by eve-seat** [comment]
Thanks. Closing.
