### ISSUE TITLE
[ENHANCEMENT] Siphon Warning

### ISSUE THREAD

**Issue by AquilaSagitta** [eve-seat/seat#419]
Would love there to be a red warning label on towers that are being siphoned. It could be placed between the in the 'State' column between 'Online' and the details anchor button. http://puu.sh/kw70V/31b2e184cf.png pic for clarification.

Simple way to check is if moon harvesting array is putting less than 100 units into silo every hour.

**Comment by MaxRink** [comment]
related: 
THIRD PARTY DEVELOPERS:
XML API:

    The API no longer makes any attempt to fake the quantity of materials being stolen by siphon units.
https://community.eveonline.com/news/patch-notes/patch-notes-for-parallax

So its even easier to implement

**Comment by eve-seat** [comment]
Thanks for the heads up. Will see what we can do in SeAT 1.x
