### ISSUE TITLE
api link in key creation 404's

### ISSUE THREAD

**Issue by volster** [eve-seat/seat#420]
In their infinite wisdom, ccp decided to change the "create predefined key" link without putting in a redirect, so it just 404's. 

old link (currently in seat)
https://support.eveonline.com/api/key/CreatePredefined/

New link 
https://community.eveonline.com/support/api-key/CreatePredefined/?accessmask=

**Comment by volster** [comment]
Also not strictly related, but if you've got to tinker with the links it seems silly not to bring it up.

The full link needs to be 1073741823 to grab the new chat channel & bookmark endpoints

**Comment by eve-seat** [comment]
Will get updated in v1.x
