### ISSUE TITLE
Won't update api info

### ISSUE THREAD

**Issue by emrysalf** [eve-seat/seat#421]
o/ Salutations,
Using CentOS 6.4 I have run into an issue where the data gets very stale.. It adds new users alright but never refreshes... I have dug around and found that someone used the command:
php artisan seatscheduled:api-update-all-characters
Which worked.. I assume that:
Corporation Updater
Corporation Assets Updater
Eve Updater
Map Updater
Server Updater
Notification Updater
Queue Cleaner
are dormant as well... 

/app/storage/logs/laravel.log

[2015-11-03 13:05:02] production.ERROR: exception 'InvalidArgumentException' with message 'There are no commands defined in the "seatscheduled" namespace.

Did you mean this?
scheduled' in /home/SeAT
/vendor/symfony/console/Symfony/Component/Console/Application.php:514
Stack trace:
#0 /home/SeAT/vendor/symfony/console/Symfony/Component/Console/Application.php(548): Symfony\Component\Console\Application->findNamespace('seatscheduled')
#1 /home/SeAT/vendor/symfony/console/Symfony/Component/Console/Application.php(188): Symfony\Component\Console\Application->find('seatscheduled:a...')
#2 /home/SeAT/vendor/symfony/console/Symfony/Component/Console/Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/SeAT/artisan(58): Symfony\Component\Console\Application->run()
#4 {main} [] []
[2015-11-03 13:10:02] production.ERROR: exception 'InvalidArgumentException' with message 'There are no commands defined in the "seatscheduled" namespace.

Did you mean this?
scheduled' in /home/SeAT/vendor/symfony/console/Symfony/Component/Console/Application.php:514
Stack trace:
#0 /home/SeAT/vendor/symfony/console/Symfony/Component/Console/Application.php(548): Symfony\Component\Console\Application->findNamespace('seatscheduled')
#1 /home/SeAT/vendor/symfony/console/Symfony/Component/Console/Application.php(188): Symfony\Component\Console\Application->find('seatscheduled:a...')
#2 /home/SeAT/vendor/symfony/console/Symfony/Component/Console/Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/SeAT/artisan(58): Symfony\Component\Console\Application->run()
#4 {main} [] []
[2015-11-03 13:10:12] production.INFO: Started command seatscheduled:api-update-all-characters {"src":"Seat\Commands\Scheduled\EveCharacterUpdater"} []

**Comment by eve-seat** [comment]
The log entry looks like there was a problem when manually running a command but is not really clear as to *what* was wrong. As for the data remaining stale, is your cronjob working and workers started?

**Comment by emrysalf** [comment]
well I sorted this by using ubuntu OS and everything was smooth and installed great!!
