### ISSUE TITLE
Error 500 when trying to open Coprcontractpage

### ISSUE THREAD

**Issue by MaxRink** [eve-seat/seat#422]
im getting a error 00 when im trying to access the contractpage of one of my corps. the other ones work fine though (might be related to a few thousand contracts on that corp)

**Comment by clonerworks** [comment]
Do you have the logs when you get the error so that we can see if the error is been logged?

**Comment by MaxRink** [comment]
[2015-11-04 09:45:09] production.ERROR: exception 'ErrorException' with message 'Missing argument 1 for CorporationController::getContracts()' in /var/www/blacklistdot/seat/app/controllers/CorporationController.php:426
Stack trace:
#0 /var/www/blacklistdot/seat/app/controllers/CorporationController.php(426): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', '/var/www/blackl...', 426, Array)
#1 [internal function]: CorporationController->getContracts()
#2 /var/www/blacklistdot/seat/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /var/www/blacklistdot/seat/bootstrap/compiled.php(5437): Illuminate\Routing\Controller->callAction('getContracts', Array)
#4 /var/www/blacklistdot/seat/bootstrap/compiled.php(5425): Illuminate\Routing\ControllerDispatcher->call(Object(CorporationController), Object(Illuminate\Routing\Route), 'getContracts')
#5 /var/www/blacklistdot/seat/bootstrap/compiled.php(4657): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CorporationCont...', 'getContracts')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /var/www/blacklistdot/seat/bootstrap/compiled.php(4984): call_user_func_array(Object(Closure), Array)
#8 /var/www/blacklistdot/seat/bootstrap/compiled.php(4682): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /var/www/blacklistdot/seat/bootstrap/compiled.php(4670): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/blacklistdot/seat/bootstrap/compiled.php(706): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/blacklistdot/seat/bootstrap/compiled.php(687): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/blacklistdot/seat/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/blacklistdot/seat/bootstrap/compiled.php(1146): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/blacklistdot/seat/bootstrap/compiled.php(7311): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/blacklistdot/seat/bootstrap/compiled.php(7908): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/blacklistdot/seat/bootstrap/compiled.php(7855): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/blacklistdot/seat/bootstrap/compiled.php(10941): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/blacklistdot/seat/bootstrap/compiled.php(648): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#19 /var/www/blacklistdot/seat/public/index.php(49): Illuminate\Foundation\Application->run()
#20 {main} [] []

**Comment by clonerworks** [comment]
It sounds like the $corporationID argument for the function getContracts is empty.

**Comment by MaxRink** [comment]
inside the DB the corpid is present though

**Comment by eve-seat** [comment]
Err. From that error it looks like the url does not have the corpID in it (which is the first arg for the getContracts method). Not 100% sure what the issue is here.

**Comment by MaxRink** [comment]
the corpid is included in the URL.

**Comment by MaxRink** [comment]
Just had enought time to look into it myself. is a pretty simple error: i go that many contracts on that api so that the php process wantet to allocate over 512mb of RAM.

**Comment by eve-seat** [comment]
Thanks. SeAT 1.x will paginate this one.
