### ISSUE TITLE
Wallet Journal data not displayed (corporations or characters)

### ISSUE THREAD

**Issue by zino73** [eve-seat/seat#423]
hello,

i installed a new Seat instance (0.14.1) on  Ubuntu 15.10 x64. 

Most feature works except :

- Seat not pulled the  lines of Wallet Journal (https://i.imgur.com/aEoLfUf.png) (**Solved see bellow**)
- when i clicked on "contracts" i have an error 500 (after a long loading)
- I am forced to manually start the data refresh (by clicking on Updtae Key now Button ) (**Solved see bellow**)

I maybe misconfigured something?

**Comment by zino73** [comment]
i don't have Wallet Transactions too

**Comment by eve-seat** [comment]
How old is the SeAT install?

**Comment by zino73** [comment]
i installed around 7 days ago

**Comment by zino73** [comment]
this thinks never worked

**Comment by zino73** [comment]
ok i looked in the table corporation_walletjournal and I find that I have many lines in it

**Comment by eve-seat** [comment]
any more debugging you can give us? log extracts or something?

**Comment by zino73** [comment]
what logs? pheal_error.log or another logs?

**Comment by MaxRink** [comment]
the actual error should be logged in the laravel.log file (its in app/storage/logs)

**Comment by lexcomman** [comment]
I have the same thing. My pheal_error.log shows:
Tue, 10 Nov 2015 00:01:06 +0000 [GET] 0.5732s https://api.eveonline.com/corp/Locations.xml.aspx?characterID=1611647779&ids=1003305640331&keyID=1735832&vCode=RLmCkpEyyQekeCfh... "221: Illegal page request! Please verify the access grante$
.........
This is on a full access api key.

**Comment by zino73** [comment]
Hello,



Thisi is my  pheal_error.log (Keyid anonymized ) :

**Comment by MaxRink** [comment]
like i said earlier, have a loom into the laravellogs and into the php-errorlog

**Comment by zino73** [comment]
oh yes sorry for laravel.log i have lot of errors when i manually launch update data keys :
lot of :
[2015-11-08 08:26:17] production.WARNING: Processing a ban request for api: Contracts scope: Corp owner: 6666666 {"src":"Seat\\EveApi\\BaseApi"} []
[2015-11-10 06:42:59] production.WARNING: Processing a ban request for api: Contracts scope: Corp owner: 6666666 {"src":"Seat\\EveApi\\BaseApi"} []
[2015-11-10 13:32:22] production.ERROR: exception 'Illuminate\Session\TokenMismatchException' in /var/www/seat/app/filters.php:193
Stack trace:
#0 [internal function]: {closure}(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#1 /var/www/seat/bootstrap/compiled.php(5841): call_user_func_array(Object(Closure), Array)
#2 /var/www/seat/bootstrap/compiled.php(5823): Illuminate\Events\Dispatcher->fire('router.filter: ...', Array, true)
#3 /var/www/seat/bootstrap/compiled.php(4847): Illuminate\Events\Dispatcher->until('router.filter: ...', Array)
#4 /var/www/seat/bootstrap/compiled.php(5499): Illuminate\Routing\Router->callRouteFilter('csrf', Array, Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#5 /var/www/seat/bootstrap/compiled.php(5443): Illuminate\Routing\ControllerDispatcher->callFilter(Array, Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#6 /var/www/seat/bootstrap/compiled.php(5423): Illuminate\Routing\ControllerDispatcher->before(Object(SessionController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'postSignIn')
#7 /var/www/seat/bootstrap/compiled.php(4657): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'SessionControll...', 'postSignIn')
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#9 /var/www/seat/bootstrap/compiled.php(4984): call_user_func_array(Object(Closure), Array)
#10 /var/www/seat/bootstrap/compiled.php(4682): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 /var/www/seat/bootstrap/compiled.php(4670): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#12 /var/www/seat/bootstrap/compiled.php(706): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 /var/www/seat/bootstrap/compiled.php(687): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 /var/www/seat/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/seat/bootstrap/compiled.php(1146): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/seat/bootstrap/compiled.php(7311): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/seat/bootstrap/compiled.php(7908): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/seat/bootstrap/compiled.php(7855): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/seat/bootstrap/compiled.php(10941): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/seat/bootstrap/compiled.php(648): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#21 /var/www/seat/public/index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []

**Comment by zino73** [comment]
ok i have solved the WalletTransaction problem by running the following command on server : 
php artisan seat:clear-cache
artisan seat:api-update

For the error when i click on corporations > contratcs , this action generate the following error in laravel.log file: 
[2015-11-10 17:14:54] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Maximum execution time of 30 seconds exceeded' in /var/www/seat/app/controllers/CorporationController.php:543
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []


How can i increase the execution time (i have a lot of corporation's contracts ) ?

**Comment by MaxRink** [comment]
in your php.ini and depending on your webserver inside the cli-configuration
http://stackoverflow.com/questions/16171132/how-to-increase-maximum-execution-time-in-php

**Comment by zino73** [comment]
ok thanks,

is it possible to schedule the api data refresh ? because my data never refresh i have to refresh manually.

**Comment by clonerworks** [comment]
Have you configured Cron jobs? They should execute code to refresh your dataset for you.

**Comment by zino73** [comment]
i htink yes, but how can i do to check if are corrected configured?

**Comment by clonerworks** [comment]
can you post your cron file and also the locate of the install directory (full path) so we can see.

**Comment by zino73** [comment]
when i type : 
crontab -l

i obtain :
no crontab for root

**Comment by MaxRink** [comment]
because u need to query the cronjobs for -u www-data
And that is not your problem, as you wrote that the DB is actually populated

**Comment by zino73** [comment]
thanks,

the database is populated because i update the keys data manually.. and when i type :+1: 
crontab -l -u www-data

i obtain :
no crontab for www-data

i think i have problem with my cronjobs no?

**Comment by MaxRink** [comment]
the enter the cronjob via crontab -e -u www-data

**Comment by zino73** [comment]
done (and i think is worked ! 
i was not really understand the procedure in the install doc, i was typed : 
crontab -u www-data -e  * * * * * /usr/bin/php /var/www/seat/artisan scheduled:run 1>> /dev/null 2>&1

that's why not worked .

Now with crontab -u www-data -e  
then added to file that edited the line :
 * * * * * /usr/bin/php /var/www/seat/artisan scheduled:run 1>> /dev/null 2>&1

now is ok !

Thanks a lot.

**Comment by lexcomman** [comment]
Wanted to update the status of my wallet journal. After performing the cache clear, and allowed everything to update again, the wallet journal would display correctly. Thank You.
