### ISSUE TITLE
Notice. SeAT 1.x is out.

### ISSUE THREAD

**Issue by eve-seat** [eve-seat/seat#426]
As the title says, 1x is out and all development efforts have gone into that. It is the latest version of SeAT, no longer considered to be a beta.

Go get it here [https://github.com/eveseat/seat](https://github.com/eveseat/seat).

This code repository will remain for historical purposes but will no longer be receiving updates. I will use the issue tracker to ensure that the problems highlighted here are fixed in 1.x though.

Thanks to everyone that tested this 0x the last few months.

If you liked SeAT, consider donating to qu1ckkkk in game.

**Comment by MorganJohnstone87** [comment]
Sweet! Getting ready to do it now. :)

--- --- --- --- ---

Morgan Johnstone
