### ISSUE TITLE
[Enhancement] Account billing overview

### ISSUE THREAD

**Issue by NovaNine** [eve-seat/seat#428]
I'm not sure if this would be best as a column in the APIs or its own page or something, but it would be very handy to see an overview of the remaining billing time on all the EVE accounts entered into my SEAT account.  Basically a summary of the paid info visible on each character detail, but shown in a single table (very useful for those of us who PLEX large #s of accounts)

**Comment by warlof** [comment]
/account/AccountStatus.xml.aspx with paidUntil
