### ISSUE TITLE
Include a better User-Agent PhealNG

### ISSUE THREAD

**Issue by Regner** [eve-seat/seat#429]
Most (over 60%) of the SEAT installs out there seem to have the stock contact information for the user agent of "seatadmin@localhost.local". Can you better encourage people to update this information? There are a few instances of SEAT doing some weird things and I would like to poke people. :)

**Comment by MilosRasic** [comment]
Oh, boi, this is like police knocking on your door :)

This might be a slight problem for people running custom versions like myself. Based on an old version of SeAT, mine seems to override phealng's http_user_agent setting in app/eveapi/BaseAPI.php with:
`PhealConfig::getInstance()->http_user_agent = 'SeAT ' . \Config::get('seat.version') . 'API Fetcher';`

This should have been generating 'SeAT unknown API Fetcher' user agent string from my instance of SeAT. Changed to include a contact email now. Hopefully this is the correct place where user agent is set. Can't find it anywhere else.

**Comment by Regner** [comment]
The top 60% of user agents for SeAT specifically have the seatadmin@localhost.local in the header. So I assume this most instances are on at least those versions. 50% of the SeAT requests come from 2 versions with that default header.

**Comment by eve-seat** [comment]
@Regner thanks for this heads up. Could you paste the full user agent you are getting?

I think 2 major things are at play here.

- First of all, this version of SeAT being 0.x is actually deprecated in favor of 1x [here](https://github.com/eveseat/seat). So ideally no new code should really be landing in this repository. I have been wondering about making a commit that will not make it possible to run this version of SeAT anymore, forcing an install of 1.x. That of course does not solve it for existing installs. This brings me to the second point.
- What exactly is the problem that you are seeing? If its something we can fix in code then that would of course be great for us.

As far as the user agent specification goes, I think the best would then be for us to add a hard requirement to set the email address as part of the installation procedure in 1.x which is easy enough to do.

@MilosRasic the user agent is actually defined in this [whole block](https://github.com/eve-seat/seat/blob/master/app/eveapi/BaseAPI.php#L67-L76) taking the mail settings into account to set a technical contact and falling back to the actual mail from in the mail settings file / environment.

Happy to discuss this further to get to a workable solution!

**Comment by Regner** [comment]
Splunk search for the past 24 hours: `index=api UserAgent = "PhealNG/*+eveseat/*" | top userAgent`

Results:
```
    userAgent	                                             count	 percent
    PhealNG/2.3.4+eveseat/1.0.11+seatadmin@localhost.local   2310817 33.207582
    PhealNG/2.3.4+eveseat/1.0.12+seatadmin@localhost.local   1628843 23.407279
    PhealNG/2.3.4+eveseat/1.0.8+seatadmin@localhost.local     363219  5.219636
    PhealNG/2.3.4+eveseat/1.0.10+****@****.com                361250  5.191341
    PhealNG/2.3.4+eveseat/1.0.12+****@****.com                319359  4.589347
    PhealNG/2.3.4+eveseat/1.0.11+****@****.com                289840  4.165144
    PhealNG/2.3.4+eveseat/1.0.11+****@****.com                201905  2.901475
    PhealNG/2.3.4+eveseat/1.0.12+****@****.com                159709  2.295097
    PhealNG/2.3.4+eveseat/1.0.12+****@****.com                154763  2.224021
    PhealNG/2.3.4+eveseat/1.0.12+****@****.com                134392  1.931279
```

**Comment by MilosRasic** [comment]
idgi, does Pheal further compile something like 'SeAT 1.0.11 API Fetcher at localhost.local Install mail_from seatadmin@localhost.local Administrative Contact: seatadmin@localhost.local' to something like 'PhealNG/2.3.4+eveseat/1.0.11+seatadmin@localhost.local' ?

**Comment by eve-seat** [comment]
@Regner fantastic. This is from the 1.x repository which solves a lot of problems! I added eveseat/seat#77 to track this implementation.

**Comment by eve-seat** [comment]
Before I forget, @Regner would it be possible to tell us what oddities you are seeing from SeAT in eveseat/seat#77 too?

Thanks again.

**Comment by eve-seat** [comment]
Closing this to be tracked in the 1.x codebase.

**Comment by Regner** [comment]
Sorry about that. I didn't realize you had a completely different repo for 1.x. :) Thank you very much for taking action on this, I really do appreciate it. :D
