### ISSUE TITLE
Cant read mail

### ISSUE THREAD

**Issue by goullom** [eve-seat/seat#430]
When i click on the "read" button, on the mail page, nothing happen.
What i do wrong, can you help me plz. thx

**Comment by warlof** [comment]
Are you the character api key owner ?

**Comment by goullom** [comment]
I'm the superuser.
I manage all the api.
i can see the mail list, the preview.
But when i click on the "read" button, nothing append, the code i linked to nothing.

**Comment by goullom** [comment]
Solved: web service was blocked to 1.0.2 same after the update process.
I forced and installed the web service alone.
