### ISSUE TITLE
enhancements to assets

### ISSUE THREAD

**Issue by dae-eliador** [eve-seat/seat#433]
Hi,

I have 2 enhancements to suggests about assets : 

1 / As of now, it is impossible to see assets inside the cargo hold of a ship through eve seat

2 / It would be great for corp / alliance officers/directors/admins to be able to search in all of the assets of all the characters they have access to, to see for example all assets still in a chosen station per character on 1 screen instead of having to go into each character sheet

**Comment by warlof** [comment]
This repository is no longer maintained. Please make use of the new version that can be found here: https://github.com/eveseat/seat

Could it be related to https://github.com/eveseat/seat/issues/140 ?
