### ISSUE TITLE
Wallet Transaction Search Criteria for char & corp

### ISSUE THREAD

**Issue by eve-seat** [eve-seat/seat#76]
Allow for full wallet transactions to be filtered & searched to allow for queries such the following to be run:
- How many of this item has been bought? Today? The last week? Between <time> and <time>?
- What has been bought & sold to <charactername>?
- How much has been spent? Today? The last week? Between <time> and <time>?

For corporations, these need to be further filtered on a per wallet division too.

**Comment by lexcomman** [comment]
Thought I would tag onto this as it is somewhat relevant for our use. SeAT is a fantastic looking software. We currently use EVE ECM to track tax contributions, bounty rewards etc. While the SeAT wallet journal provides all this information, what we see it lacking in for our use is the ability to filter by a specific time and date range. Is this something that could be easily implemented or modified to do?

**Comment by eve-seat** [comment]
SeAT 1.x has much improved filtering support. Will make sure its added there when I get to that part of the code.
